import DirichletSeriesSeveralComplexVariablesFoundationCanonicalLaneLean.DirichletSeriesFoundation
import DirichletSeriesSeveralComplexVariablesFoundationCanonicalLaneLean.AdmissibleClass
import DirichletSeriesSeveralComplexVariablesFoundationCanonicalLaneLean.BridgeLemmas
import DirichletSeriesSeveralComplexVariablesFoundationCanonicalLaneLean.GateLemmas
import DirichletSeriesSeveralComplexVariablesFoundationCanonicalLaneLean.ConvergenceAbscissaBridge
import DirichletSeriesSeveralComplexVariablesFoundationCanonicalLaneLean.ThetaFunctionBridge
import DirichletSeriesSeveralComplexVariablesFoundationCanonicalLaneLean.FinalTheorem

/-!
# Root module for DirichletSeriesSeveralComplexVariablesFoundationCanonicalLaneLean Lean proof package.
-/

namespace HautevilleHouse
namespace DirichletSeriesSeveralComplexVariablesFoundationCanonicalLaneLean
-- All submodules imported
end DirichletSeriesSeveralComplexVariablesFoundationCanonicalLaneLean
end HautevilleHouse
